### ISSUE TITLE
Results and logs are not recorded from some simulation runs

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2321]
Example
- [ ] https://run.biosimulations.org/simulations/605797d69ee11f86483dde5a

Here's another example which generates a different error:
- [ ] https://run.api.biosimulations.dev/results/6057976761883685e1e8c86f?sparse=true

**Comment by bilalshaikh42** [comment]
Does this happen every time? I am working on reproducing this now

**Comment by bilalshaikh42** [comment]
I see this is happening for the boolent example. This is the same error that we discussed. Here is the full trace. Some element is being added to the mongo db that has a "." in it I beleive. 

```
[Nest] 1   - 03/22/2021, 2:06:31 PM   [DefaultFilter] Error: key Time (arb.) must not contain '.' +88ms
Error: key Time (arb.) must not contain '.'
    at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:921:19)
    at serializeObject (/app/node_modules/bson/lib/bson/parser/serializer.js:347:18)
    at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:947:17)
    at serializeObject (/app/node_modules/bson/lib/bson/parser/serializer.js:347:18)
    at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:729:17)
    at serializeObject (/app/node_modules/bson/lib/bson/parser/serializer.js:347:18)
    at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:947:17)
    at BSON.serialize (/app/node_modules/bson/lib/bson/bson.js:64:28)
    at Msg.serializeBson (/app/node_modules/mongodb/lib/core/connection/msg.js:127:22)
    at Msg.makeDocumentSegment (/app/node_modules/mongodb/lib/core/connection/msg.js:119:33)
    at Msg.toBin (/app/node_modules/mongodb/lib/core/connection/msg.js:105:25)
    at MessageStream.writeCommand (/app/node_modules/mongodb/lib/cmap/message_stream.js:55:28)
    at Connection.write (/app/node_modules/mongodb/lib/cmap/connection.js:368:26)
    at _command (/app/node_modules/mongodb/lib/core/wireprotocol/command.js:120:10)
    at command (/app/node_modules/mongodb/lib/core/wireprotocol/command.js:28:5)
    at writeCommand (/app/node_modules/mongodb/lib/core/wireprotocol/write_command.js:56:3)
```

**Comment by bilalshaikh42** [comment]
This error happens when the results and logs are being posted to the api.  The front end then gets the 404 page. The "log not found" was an older fallback that is now removed.

**Comment by jonrkarr** [comment]
The error still happens even without "." in the report ids.

Here's an example:
[Irons J Theor Biol 2009.zip](https://github.com/biosimulations/Biosimulations/files/6216851/Irons.J.Theor.Biol.2009.zip)
https://run.api.biosimulations.dev/logs/6060003efac07b8bb39a1f13?download=false

**Comment by jonrkarr** [comment]
This is now covered by #2440.
