### ISSUE TITLE
Simulations all stuck in processing state

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2437]
I've tried several simulations with BoolNet, PySCeS and tellurium. They're all getting stuck in the processing state. The log for the first one is below.

- http://localhost:4200/simulations/60760fcf9100bf17622f6aa6#tab=log
- http://localhost:4200/simulations/60761d629100bf6bac2f6aa9
- http://localhost:4200/simulations/60761edd9100bfd0f02f6aae
- https://run.biosimulations.org/simulations/60761f0343f34125b1d64664

```
=============Downloading Combine Archive=============
--2021-04-13 17:40:34--  https://run.api.biosimulations.dev/run/60760fcf9100bf17622f6aa6/download
Resolving run.api.biosimulations.dev (run.api.biosimulations.dev)... 34.123.157.17
Connecting to run.api.biosimulations.dev (run.api.biosimulations.dev)|34.123.157.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: 'Irons J Theor Biol 2009.omex'

     0K ....                                                   11.0M=0s

2021-04-13 17:40:34 (11.0 MB/s) - 'Irons J Theor Biol 2009.omex' saved [5058]

=============Running docker image for simulator=============
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:45b42c59be334ecda0daaa139b2f7d310e45c564c5f12263b1b8e68ec9e810ed
Copying blob sha256:f875e16ab19cd1fe91a8dec4e53d46321630bfd611851b1817341c3302f638c2
Copying blob sha256:6997dda769d87b1ae0a92d94c5c4fd5530185e377706e221127183c97f230a01
Copying blob sha256:564b60cf6c28e016e19c67b9f41cbcb64e0a31ab4fda9611ff6d75a3f166521d
Copying blob sha256:e55c09d2e3e0bbd47f085469be61562a5496be6caba50cf6dec7e244637b13e3
Copying blob sha256:d33ece5e240840b77c596cffdf63ccf7d548c7a0464ae838596832c420fb0a8a
Copying blob sha256:d78091d404cdbc3a642fc88749f5956cb6397fb39a8744ef2847842a46688bfc
Copying blob sha256:3d106c366f5ec8998bc69a2da439d6c4f45810a1cf99ea2ecde859fe08036923
Copying config sha256:4a674e523e27421889012e2dcbbbb0a559f2e072b78a7ba76d65e3a80f771e12
Writing manifest to image destination
Storing signatures
2021/04/13 17:40:40  info unpack layer: sha256:45b42c59be334ecda0daaa139b2f7d310e45c564c5f12263b1b8e68ec9e810ed
2021/04/13 17:40:40  warn xattr{/home/FCAM/crbmapi/singularity/tmp/build-temp-612339477/rootfs} ignoring ENOTSUP on llistxattr
2021/04/13 17:40:40  warn xattr{/home/FCAM/crbmapi/singularity/tmp/build-temp-612339477/rootfs/bin} destination filesystem does not support xattrs, further warnings will be suppressed
2021/04/13 17:42:36  info unpack layer: sha256:f875e16ab19cd1fe91a8dec4e53d46321630bfd611851b1817341c3302f638c2
2021/04/13 17:42:36  warn xattr{/home/FCAM/crbmapi/singularity/tmp/build-temp-612339477/rootfs} ignoring ENOTSUP on llistxattr
2021/04/13 17:42:36  warn xattr{/home/FCAM/crbmapi/singularity/tmp/build-temp-612339477/rootfs/etc} destination filesystem does not support xattrs, further warnings will be suppressed
2021/04/13 17:42:47  info unpack layer: sha256:6997dda769d87b1ae0a92d94c5c4fd5530185e377706e221127183c97f230a01
2021/04/13 17:42:47  warn xattr{/home/FCAM/crbmapi/singularity/tmp/build-temp-612339477/rootfs} ignoring ENOTSUP on llistxattr
2021/04/13 17:42:47  warn xattr{/home/FCAM/crbmapi/singularity/tmp/build-temp-612339477/rootfs/bin} destination filesystem does not support xattrs, further warnings will be suppressed
2021/04/13 17:43:20  info unpack layer: sha256:564b60cf6c28e016e19c67b9f41cbcb64e0a31ab4fda9611ff6d75a3f166521d
2021/04/13 17:43:20  warn xattr{/home/FCAM/crbmapi/singularity/tmp/build-temp-612339477/rootfs} ignoring ENOTSUP on llistxattr
2021/04/13 17:43:20  warn xattr{/home/FCAM/crbmapi/singularity/tmp/build-temp-612339477/rootfs/usr} destination filesystem does not support xattrs, further warnings will be suppressed
2021/04/13 17:43:20  info unpack layer: sha256:e55c09d2e3e0bbd47f085469be61562a5496be6caba50cf6dec7e244637b13e3
2021/04/13 17:43:20  warn xattr{/home/FCAM/crbmapi/singularity/tmp/build-temp-612339477/rootfs} ignoring ENOTSUP on llistxattr
2021/04/13 17:43:20  warn xattr{/home/FCAM/crbmapi/singularity/tmp/build-temp-612339477/rootfs/etc} destination filesystem does not support xattrs, further warnings will be suppressed
2021/04/13 17:43:44  info unpack layer: sha256:d33ece5e240840b77c596cffdf63ccf7d548c7a0464ae838596832c420fb0a8a
2021/04/13 17:43:44  warn xattr{/home/FCAM/crbmapi/singularity/tmp/build-temp-612339477/rootfs} ignoring ENOTSUP on llistxattr
2021/04/13 17:43:44  warn xattr{/home/FCAM/crbmapi/singularity/tmp/build-temp-612339477/rootfs/etc} destination filesystem does not support xattrs, further warnings will be suppressed
2021/04/13 17:54:20  info unpack layer: sha256:d78091d404cdbc3a642fc88749f5956cb6397fb39a8744ef2847842a46688bfc
2021/04/13 17:54:20  warn xattr{/home/FCAM/crbmapi/singularity/tmp/build-temp-612339477/rootfs} ignoring ENOTSUP on llistxattr
2021/04/13 17:54:20  warn xattr{/home/FCAM/crbmapi/singularity/tmp/build-temp-612339477/rootfs/root} destination filesystem does not support xattrs, further warnings will be suppressed
2021/04/13 17:54:23  info unpack layer: sha256:3d106c366f5ec8998bc69a2da439d6c4f45810a1cf99ea2ecde859fe08036923
2021/04/13 17:54:23  warn xattr{/home/FCAM/crbmapi/singularity/tmp/build-temp-612339477/rootfs} ignoring ENOTSUP on llistxattr
2021/04/13 17:54:23  warn xattr{/home/FCAM/crbmapi/singularity/tmp/build-temp-612339477/rootfs/root} destination filesystem does not support xattrs, further warnings will be suppressed
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** JOB 2896397 ON xanadu-55 CANCELLED AT 2021-04-13T18:00:41 DUE TO TIME LIMIT ***
slurmstepd: error: *** STEP 2896397.1 ON xanadu-55 CANCELLED AT 2021-04-13T18:00:41 DUE TO TIME LIMIT ***
```

**Comment by bilalshaikh42** [comment]
Just to clarify, are you running these on local host? The  dispatch service will not be able to read the output files since it is relying on an NFS mount to uconn. This is the last part of the system that depends on the mount, (issue #2069 ). The processing step won't be successful.

Since I made the change to process the result upload independently it might now timeout rather than just failing. I can check on that.  It also seems like this was the first run of a new image, so the image had to be compiled, which may have just been the source of the timeout.

**Comment by bilalshaikh42** [comment]
I am able to run the simulation on the deployment just fine here 
https://run.biosimulations.dev/simulations/60763500aae5614fe1bf0c4b

**Comment by bilalshaikh42** [comment]
I see, I am able to reproduce the issue on the .org domain.  Here is the error that we are getting. I am not sure anymore how far the org deployment is from the dev, but we should update it. This error would have been caught and caused the job to fail on the current dev deployment.
```
{
  "error": [
    {
      "status": "400",
      "title": "Parse Error",
      "detail": "Inconsistent datatypes for key ",
      "source": {
        "pointer": "/\"Phosphorylated"
      },
      "meta": {
        "time": 1618359922154,
        "url": "/results/6076366843f3415adfd64669/simulation_1.sedml%2Fsimulation_1"
      }
    }
  ]
}
```

**Comment by bilalshaikh42** [comment]
Though it seems we have a different issue on the dev deployment. 

```
 Error: key Time (arb.) must not contain '.' +648ms
Error: key Time (arb.) must not contain '.'
    at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:921:19)
    at serializeObject (/app/node_modules/bson/lib/bson/parser/serializer.js:347:18)
    at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:947:17)
    at serializeObject (/app/node_modules/bson/lib/bson/parser/serializer.js:347:18)
    at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:729:17)
    at serializeObject (/app/node_modules/bson/lib/bson/parser/serializer.js:347:18)
    at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:947:17)
    at BSON.serialize (/app/node_modules/bson/lib/bson/bson.js:64:28)
    at Msg.serializeBson (/app/node_modules/mongodb/lib/core/connection/msg.js:127:22)
    at Msg.makeDocumentSegment (/app/node_modules/mongodb/lib/core/connection/msg.js:119:33)
    at Msg.toBin (/app/node_modules/mongodb/lib/core/connection/msg.js:105:25)
    at MessageStream.writeCommand (/app/node_modules/mongodb/lib/cmap/message_stream.js:55:28)
    at Connection.write (/app/node_modules/mongodb/lib/cmap/connection.js:368:26)
    at _command (/app/node_modules/mongodb/lib/core/wireprotocol/command.js:120:10)
    at command (/app/node_modules/mongodb/lib/core/wireprotocol/command.js:28:5)
    at writeCommand (/app/node_modules/mongodb/lib/core/wireprotocol/write_command.js:56:3)
[Nest] 1   - 04/14/2021, 12:06:56 AM   [DefaultFilter] Object:
{
  "error": [
    {
      "status": "500",
      "title": "Internal Server Error",
      "meta": {
        "time": 1618358816781,
        "url": "/results/60763213aae561b29dbf0c40/simulation.sedml%2Freport_del_Cln2"
      }
    }
  ]
}
```

**Comment by jonrkarr** [comment]
I tried local and .org. I tried the simulation with "." in the id and one of the example simulations that we've run previously with 3 tools.

Is the key with "." being used in logs or results?

The .org deployment is old. This can definitely be updated.

**Comment by bilalshaikh42** [comment]
This key with "." is being uploaded to results. (It seems the field is
called Time (arb.) ) or something along those lines.

**Comment by jonrkarr** [comment]
I thought this was changed with the new data model for results. It sounds like there's still a data model somewhere that needs to be converted from a dictionary to a list of objects.

**Comment by bilalshaikh42** [comment]
Yes, the data is returned in the new structure but still stored in the old way.  I'll create an issue to fix that. 
This issue has been resolved as now the simulation will be marked as failed as it should be. I had some confusion on the error handling due to returning  Promise<void> by having an  async function return 'void'  as opposed to  returning a Promise that resolves to void.  The type checking cannot distinguish those two cases and causes a difference in how errors are passed up. 

Anyway, the simulations are now correctly marked as failed, but the user sees no reason for this failure since the API error message is returned to the service. I will create an issue to incorporate this information into the log.yml.  This will also help resolve some of the confusion caused by the log.yml stating success while the status is failed

**Comment by jonrkarr** [comment]
Thanks. Feel free to change the structure of the log or create an issue for me to make a change. 

I'm getting starting on the last topic for the revision -- improving error messages from the simulation tools, plus still trying to wrap up the display of plots described in SBML.

**Comment by jonrkarr** [comment]
Didn't intend reopen this.
