### ISSUE TITLE
Error Running simulation with Neuron

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2616]
Running simulations with Neruon fails (https://run.biosimulations.dev/simulations/60ba7d2672a58d7079feebaa)

Here is the error: 

```

INFO:    Using cached SIF image
(EE) 
Fatal server error:
(EE) Server is already active for display 1
        If this server is no longer running, remove /tmp/.X1-lock
        and start again.
(EE) 

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/opt/conda/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/opt/conda/lib/python3.8/site-packages/conda/cli/main_run.py", line 25, in execute
        script_caller, command_args = wrap_subprocess_call(on_win, context.root_prefix, prefix,
      File "/opt/conda/lib/python3.8/site-packages/conda/utils.py", line 403, in wrap_subprocess_call
        with Utf8NamedTemporaryFile(mode='w', prefix=tmp_prefix, delete=False) as fh:
      File "/opt/conda/lib/python3.8/site-packages/conda/_vendor/auxlib/compat.py", line 81, in Utf8NamedTemporaryFile
        return NamedTemporaryFile(mode=mode, buffering=buffering, encoding=encoding,
      File "/opt/conda/lib/python3.8/tempfile.py", line 541, in NamedTemporaryFile
        (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
      File "/opt/conda/lib/python3.8/tempfile.py", line 250, in _mkstemp_inner
        fd = _os.open(file, flags, 0o600)
    OSError: [Errno 30] Read-only file system: '/opt/conda/envs/py39/.tmps3h5iamp'

`$ /opt/conda/bin/conda run --no-capture-output -n py39 biosimulators-neuron -i /root/Hodgkin-Huxley-cell-CVODE.omex -o /root`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/opt/conda
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/.singularity.d/libs
               MODULEPATH=/home/FCAM/crbmapi/module/
                     PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin
                          :/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
                USER_PATH=/home/FCAM/crbmapi/module/3.7.1/bin:/usr/local/bin:/usr/bin:/usr/sbin/
                          :/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin

     active environment : None
       user config file : /home/FCAM/crbmapi/.condarc
 populated config files : 
          conda version : 4.10.1
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.28=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda  (read only)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/FCAM/crbmapi/.conda/pkgs
       envs directories : /home/FCAM/crbmapi/.conda/envs
                          /opt/conda/envs
               platform : linux-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.8.5 Linux/3.10.0-1062.12.1.el7.x86_64 debian/10 glibc/2.28
                UID:GID : 16997:10000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

/xvfb-startup.sh: line 6: kill: (506832) - No such process
srun: error: xanadu-55: task 0: Exited with exit code 1
srun: Terminating job step 3034254.1


```

This appears similar to a previous error with the startup script file. It may be in the wrong location

**Comment by jonrkarr** [comment]
Thanks. I'll try to reproduce this with Singularity. Maybe we should be running test suite with the Singularity versions of the images rather than the Docker versions.

**Comment by jonrkarr** [comment]
I think the issue is with permissions to the conda environment
```
OSError: [Errno 30] Read-only file system: '/opt/conda/envs/py39/.tmps3h5iamp'
```

Specifically, it seems to be related to activation of the conda environment. I think I've gotten around this by directly executing the version of Python in the conda environment.
