### ISSUE TITLE
Dispatch APIs down (dev and org)

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2688]
The Dispatch APIs are down
- https://run.api.biosimulations.org/
- https://run.api.biosimulations.dev/

The APIs are returning these errors
- 502 Bad Gateway
- 504 Gateway Time-out

**Comment by jonrkarr** [comment]
Maybe related to this error in serving the dispatch api
```
[Nest] 19815  - 07/13/2021, 3:17:12 PM   ERROR [ExceptionHandler] natsPackage.JSONCodec is not a function
TypeError: natsPackage.JSONCodec is not a function
    at new NatsJSONSerializer (/home/jonrkarr/Documents/Biosimulations/node_modules/@nestjs/microservices/serializers/nats-json.serializer.js:9:38)
    at ClientNats.initializeSerializer (/home/jonrkarr/Documents/Biosimulations/node_modules/@nestjs/microservices/client/client-nats.js:121:136)
    at new ClientNats (/home/jonrkarr/Documents/Biosimulations/node_modules/@nestjs/microservices/client/client-nats.js:18:14)
    at Function.create (/home/jonrkarr/Documents/Biosimulations/node_modules/@nestjs/microservices/client/client-proxy-factory.js:23:24)
    at InstanceWrapper.useFactory [as metatype] (/home/jonrkarr/Documents/Biosimulations/dist/apps/dispatch-api/webpack:/libs/shared/nats-client/src/lib/shared-nats-client.module.ts:16:35)
    at Injector.instantiateClass (/home/jonrkarr/Documents/Biosimulations/node_modules/@nestjs/core/injector/injector.js:290:55)
    at callback (/home/jonrkarr/Documents/Biosimulations/node_modules/@nestjs/core/injector/injector.js:43:41)
    at Injector.resolveConstructorParams (/home/jonrkarr/Documents/Biosimulations/node_modules/@nestjs/core/injector/injector.js:115:24)
    at Injector.loadInstance (/home/jonrkarr/Documents/Biosimulations/node_modules/@nestjs/core/injector/injector.js:47:9)
    at Injector.loadProvider (/home/jonrkarr/Documents/Biosimulations/node_modules/@nestjs/core/injector/injector.js:69:9)
    at async Promise.all (index 3)
    at InstanceLoader.createInstancesOfProviders (/home/jonrkarr/Documents/Biosimulations/node_modules/@nestjs/core/injector/instance-loader.js:44:9)
    at /home/jonrkarr/Documents/Biosimulations/node_modules/@nestjs/core/injector/instance-loader.js:29:13
    at async Promise.all (index 8)
    at InstanceLoader.createInstances (/home/jonrkarr/Documents/Biosimulations/node_modules/@nestjs/core/injector/instance-loader.js:28:9)
    at InstanceLoader.createInstancesOfDependencies (/home/jonrkarr/Documents/Biosimulations/node_modules/@nestjs/core/injector/instance-loader.js:18:9)
```

**Comment by bilalshaikh42** [comment]
I believe that error should go away with a fresh npm-install. The issue on
the deployment is different. The apps are not able to connect to the
message broker. I updated the broker and the config to see if that
resolves it.

**Comment by jonrkarr** [comment]
I tried that a couple of times. I think I got past the JSONCodec issue.

Now I see another issue. Not sure if this is related to secrets. 
```
(node:24415) UnhandledPromiseRejectionWarning: NatsError: CONNECTION_REFUSED
    at Function.errorForCode (/home/jonrkarr/Documents/Biosimulations/node_modules/nats/nats-base-client/error.ts:115:12)
    at NodeTransport.<anonymous> (/home/jonrkarr/Documents/Biosimulations/node_modules/nats/src/node_transport.ts:82:21)
    at Generator.throw (<anonymous>)
    at rejected (/home/jonrkarr/Documents/Biosimulations/node_modules/nats/lib/src/node_transport.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by bilalshaikh42** [comment]
This is the issue that I am running into in the deployment, but I am unable to replicate it locally. Are you running the NATS docker image locally?

**Comment by jonrkarr** [comment]
No

**Comment by jonrkarr** [comment]
Wasn't aware I needed to

**Comment by bilalshaikh42** [comment]
Resolved in https://github.com/biosimulations/Biosimulations/commit/1851742fdb222a6330a6b2f52b814ee7d3273c5a
Need to run a couple of simulations to confirm all messaging is working correctly.

**Comment by bilalshaikh42** [comment]
> Wasn't aware I needed to

Two options here. For both, the nats server will be located at `NATS://localhost:4222`
To run a nats server locally (isolated from the deployments messages): 
```bash 
  docker run  -p 4222:4222 nats 
```

To connect to the nats-server running in the dev deployment (messages sent from local will be received by deployment and vice-versa): 

```bash
gcloud container clusters get-credentials biosimulations --zone us-central1-c --project biosimulations  && kubectl port-forward --namespace dev $(kubectl get pod --namespace dev --selector="app=nats,nats_cluster=nats-cluster" --output jsonpath='{.items[0].metadata.name}') 4222:4222
```

**Comment by jonrkarr** [comment]
Thanks!
