### ISSUE TITLE
Simulators API reruns 500 due to invalid semver version 

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3008]
API is currently returning 500s due to a simulator that has the version 7.4.0.22.1 which causes an error when trying to sort by version.

Need to catch the error and use an alternative way to sort in cases where the version is not compatible with semver.

**Comment by jonrkarr** [comment]
(a) Here's another package which supports more points:
https://www.npmjs.com/package/tiny-version-compare

(b) If tiny-version-compare or compare-versions raises an exception, the most recent submission could be returned (i.e., sort by `Simulator.biosimulators.created`). This would ensure that simulators whose version tags don't conform to our expectations can still be sorted, albeit not necessarily in the most semantically meaningful way.

**Comment by jonrkarr** [comment]
Error still present

**Comment by bilalshaikh42** [comment]
The package dependencies were not installed correctly/ the import did not
work correctly

Here is the error

```

internal/modules/cjs/loader.js:892
25
  throw err;
24
  ^
23
22
Error: Cannot find module 'tiny-version-compare'
21
Require stack:
20
- /app/main.js
19
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
18
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
17
    at Module.require (internal/modules/cjs/loader.js:961:19)
16
    at require (internal/modules/cjs/helpers.js:92:18)
15
    at Object.<anonymous> (/app/main.js:7950:18)
14
    at __webpack_require__ (/app/main.js:20:30)
13
    at Object.<anonymous> (/app/main.js:6726:78)
12
    at __webpack_require__ (/app/main.js:20:30)
11
    at Object.<anonymous> (/app/main.js:6675:80)
10
    at __webpack_require__ (/app/main.js:20:30)
9
    at Object.<anonymous> (/app/main.js:6388:87)
8
    at __webpack_require__ (/app/main.js:20:30)
7
    at Module.<anonymous> (/app/main.js:8328:73)
6
    at __webpack_require__ (/app/main.js:20:30)
5
    at Object.<anonymous> (/app/main.js:8313:18)
4
    at __webpack_require__ (/app/main.js:20:30) {
3
  code: 'MODULE_NOT_FOUND',
2
  requireStack: [ '/app/main.js' ]
```

This actually has caused the container to crash entirely.

**Comment by jonrkarr** [comment]
Does this need to be moved from a `dev` dependencies to a regular dependency?

**Comment by bilalshaikh42** [comment]
Ah, I didn't notice that. Yes, it would need to be a regular dependency.
I'll put the change back in

**Comment by jonrkarr** [comment]
I forgot this was going to be deployed in the backend rather than in browsers.

This package did work for me locally. I think it should work fine once the dependency type is corrected.

I setup the new package to work as a fallback when compare-versions fails. If the new package fails, we can compare submission dates. Beyond that, simulators developers need to do something sensical.
