### ISSUE TITLE
Simulation results cannot be retrieved

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3313]
Example: https://api.biosimulations.dev/results/616de17a263a325175111d93/simulation_1.sedml%2Freport?includeData=true

```
[31m[Nest] 1  - [39m10/18/2021, 9:06:17 PM [31m  ERROR[39m [38;5;3m[ResultsService] [39m[31mError parsing data due to inconsistent atributes and values. Recieved ids, labels, shapes, names,types:[39m
[31m[Nest] 1  - [39m10/18/2021, 9:06:17 PM [31m  ERROR[39m [38;5;3m[ResultsService] [39m[31mdata_set_time,data_set_Cdc20a,data_set_BE,data_set_Cdc20,data_set_Trim,data_set_Cdh1,data_set_Clb,data_set_Cln,data_set_IE,data_set_mass,data_set_Mcm,data_set_Mih1a,data_set_Swe1M,data_set_PTrim,data_set_PClb,data_set_PSwe1,data_set_PSwe1M,data_set_SBF,data_set_Sic,data_set_Swe1,data_set_Swe1T[39m
[31m[Nest] 1  - [39m10/18/2021, 9:06:17 PM [31m  ERROR[39m [38;5;3m[ResultsService] [39m[31mTime (min),Activated Cdc20,BE,Cdc20,CDC28-Clb2-Sic1,Cdh1,Clb2,Cln,Intermediary enzyme,Mass,Mcm,Mih1a,Modified Swe1,Phosphorylated Cdc28-Clb2-Sic1,Phosphorylated Clb2,Phosphorylated Swe1,Phosphorylated, modified Swe1,SBF,Sic1,Swe1,Total Swe1[39m
[31m[Nest] 1  - [39m10/18/2021, 9:06:17 PM [31m  ERROR[39m [38;5;3m[ResultsService] [39m[31m201,201,201,201,201,201,201,201,201,201,201,201,201,201,201,201,201,201,201,201,201[39m
[31m[Nest] 1  - [39m10/18/2021, 9:06:17 PM [31m  ERROR[39m [38;5;3m[ResultsService] [39m[31m,,,,,,,,,,,,,,,,,,,,[39m
[31m[Nest] 1  - [39m10/18/2021, 9:06:17 PM [31m  ERROR[39m [38;5;3m[ResultsService] [39m[31mfloat64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64[39m
[31m[Nest] 1  - [39m10/18/2021, 9:06:17 PM [31m  ERROR[39m [38;5;3m[ResultsService] [39m[31m0[39m
[31m[Nest] 1  - [39m10/18/2021, 9:06:17 PM [31m  ERROR[39m [38;5;3m[DefaultFilter] [39m[31mError: Cannot process data[39m
Error: Cannot process data
    at ResultsService.<anonymous> (/app/main.js:3060:23)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[32m[Nest] 1  - [39m10/18/2021, 9:06:17 PM [32m    LOG[39m [38;5;3m[DefaultFilter] [39m[32mObject:[39m
{
  "error": [
    {
      "status": "500",
      "title": "Internal Server Error",
      "meta": {
        "time": 1634591177233,
        "url": "/results/616de17a263a325175111d93/simulation_1.sedml%2Freport?includeData=true"
      }
    }
  ]
}
```

**Comment by bilalshaikh42** [comment]
Seems this is due to the labels and datasets not being the same length?

**Comment by jonrkarr** [comment]
I think they're the same length. One of the labels has a comma in it ("Phosphorylated, modified Swe1").

**Comment by bilalshaikh42** [comment]
Ah I see. Let me look at the code and make sure that isn't the cause

**Comment by bilalshaikh42** [comment]
Found the issue, there was a typo in the schema that I used to generate the client
