### ISSUE TITLE
COMBINE API appears to silently fail to receive configuration/secret files

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3813]
The COMBINE API needs to read `secret/secret.env` and `config/config.env`. 

```
[2021-12-15 19:04:56,303] ERROR in app: Exception on /combine/create [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/connexion/decorators/decorator.py", line 68, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.9/site-packages/connexion/decorators/uri_parsing.py", line 149, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.9/site-packages/connexion/decorators/validation.py", line 193, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.9/site-packages/connexion/decorators/parameter.py", line 115, in wrapper
    return function(**kwargs)
  File "/app/src/handlers/combine/create.py", line 161, in handler
    archive_url = src.utils.save_file_to_s3_bucket(archive_filename, public=True)
  File "/app/src/utils.py", line 80, in save_file_to_s3_bucket
    s3_bucket = get_s3_bucket()
  File "/app/src/utils.py", line 67, in get_s3_bucket
    s3_bucket = S3Bucket()
  File "/app/src/s3.py", line 29, in __init__
    self.bucket = s3.Bucket(default_bucket)
  File "/usr/local/lib/python3.9/site-packages/boto3/resources/factory.py", line 473, in create_resource
    return partial(resource_cls, *positional_args,
  File "/usr/local/lib/python3.9/site-packages/boto3/resources/base.py", line 118, in __init__
    raise ValueError(
ValueError: Required parameter name not set
```

This fails due to this
```python
from dotenv import dotenv_values
config = {
    **dotenv_values("secret/secret.env"),
    **dotenv_values("config/config.env"),
}
default_bucket = config.get("STORAGE_BUCKET")
s3.Bucket(default_bucket)
```

**Comment by bilalshaikh42** [comment]
There have not been any changes to this at all lately have there? It seems to me this could be a result of the container crashing issue. There can be problems with accessing config files when everything gets jammed up like that

**Comment by jonrkarr** [comment]
Correct, neither the configuration nor the method for passing configuration has changed. This also feels like the result of a performance issue with the deployment.
