### ISSUE TITLE
Production deployment appears to have failed silently

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3814]
The API and maybe other apps appear not to have been deployed with https://github.com/biosimulations/biosimulations/actions/runs/1581231059

For example, a new attribute is visible in the documentation at https://api.biosimulations.dev/#/Projects/ProjectsController_getProjectSummaries but not at https://api.biosimulations.org/#/Projects/ProjectsController_getProjectSummaries.

**Comment by bilalshaikh42** [comment]
Seems that there were quite a few crashed containers on the deployment. I cleared those out and the changes ae syncing again

**Comment by bilalshaikh42** [comment]
This might be due to the database having an older schema that is removing old fields or something along those lines. 
We can try to clear the database of the models that no longer match the schema

**Comment by jonrkarr** [comment]
I don't think its because of such as schema issue. I think some errors I saw are because I expected prod to have been deployed, but it wasn't.

**Comment by jonrkarr** [comment]
I'm still seeing an old version of code deployed on prod.

**Comment by bilalshaikh42** [comment]
I was able to trigger a deployment manually. Not sure why the API call for the workflow is not working.

**Comment by jonrkarr** [comment]
The prod API is now done. I tried restarting from Argo. The logs have these errors

```
[31m[Nest] 1  - [39m12/16/2021, 3:07:23 AM [31m  ERROR[39m [38;5;3m[ExceptionHandler] [39m[31mMust provide a clientId[39m
ArgumentError: Must provide a clientId
    at new ManagementTokenProvider (/app/node_modules/auth0/src/management/ManagementTokenProvider.js:37:11)
    at new ManagementClient (/app/node_modules/auth0/src/management/index.js:134:26)
    at new ManagementService (/app/main.js:11344:28)
    at Injector.instantiateClass (/app/node_modules/@nestjs/core/injector/injector.js:301:19)
    at callback (/app/node_modules/@nestjs/core/injector/injector.js:48:41)
    at async Injector.resolveConstructorParams (/app/node_modules/@nestjs/core/injector/injector.js:124:24)
    at async Injector.loadInstance (/app/node_modules/@nestjs/core/injector/injector.js:52:9)
    at async Injector.loadProvider (/app/node_modules/@nestjs/core/injector/injector.js:74:9)
    at async Promise.all (index 3)
    at async InstanceLoader.createInstancesOfProviders (/app/node_modules/@nestjs/core/injector/instance-loader.js:44:9)
    at async /app/node_modules/@nestjs/core/injector/instance-loader.js:29:13
    at async Promise.all (index 37)
    at async InstanceLoader.createInstances (/app/node_modules/@nestjs/core/injector/instance-loader.js:28:9)
    at async InstanceLoader.createInstancesOfDependencies (/app/node_modules/@nestjs/core/injector/instance-loader.js:18:9)
    at async /app/node_modules/@nestjs/core/nest-factory.js:93:17
    at async Function.asyncRun (/app/node_modules/@nestjs/core/errors/exceptions-zone.js:22:13)
```

**Comment by bilalshaikh42** [comment]
This is caused by the same issue. The config is not being mounted to the container

**Comment by bilalshaikh42** [comment]
I am clearing out old pods and added some resources

**Comment by bilalshaikh42** [comment]
This was due to the changes made with using auth0 for groups. The secrets were correctly added to the dev deployment, but not prod
