### ISSUE TITLE
🐛: Combine API crashing on metadata requests 

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4030]
### Location

Other (please describe below)

### What happened?

Combine API crashes  when trying to load metadata from combine archive

### What made it happen?

Running the dispatch service to process simulations. This is exacerbated by retries and the dispatch-service retries and one by one crashes each worker/pod of the combine API

### Version

Offline (Some Library, Tool, or Image not on the web)

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/connexion/decorators/decorator.py", line 68, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.9/site-packages/connexion/decorators/uri_parsing.py", line 149, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.9/site-packages/connexion/decorators/validation.py", line 193, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.9/site-packages/connexion/decorators/parameter.py", line 115, in wrapper
    return function(**kwargs)
  File "/app/src/handlers/combine/get_metadata_for_combine_archive.py", line 28, in handler_biosimulations
    el_metadatas = handler(body, file=file, omexMetadataSchema=OmexMetadataSchema.biosimulations.value)
  File "/app/src/handlers/combine/get_metadata_for_combine_archive.py", line 172, in handler
    metadata, errors, warnings = read_omex_meta_files_for_archive(archive, archive_dirname, config=config)
  File "/usr/local/lib/python3.9/site-packages/biosimulators_utils/omex_meta/io.py", line 124, in read_omex_meta_files_for_archive
    return read_omex_meta_file(filenames, archive=archive, working_dir=archive_dirname, config=config)
  File "/usr/local/lib/python3.9/site-packages/biosimulators_utils/omex_meta/io.py", line 59, in read_omex_meta_file
    return BiosimulationsOmexMetaReader().run(filename_or_filenames, archive=archive, working_dir=working_dir, config=config)
  File "/usr/local/lib/python3.9/site-packages/biosimulators_utils/omex_meta/io.py", line 462, in run
    temp_errors, temp_warnings = validate_biosimulations_metadata(el_metadatas, archive=archive, working_dir=working_dir)
  File "/usr/local/lib/python3.9/site-packages/biosimulators_utils/omex_meta/validation.py", line 46, in validate_biosimulations_metadata
    temp_errors, temp_warnings = validate_biosimulations_metadata_for_uri(
  File "/usr/local/lib/python3.9/site-packages/biosimulators_utils/omex_meta/validation.py", line 116, in validate_biosimulations_metadata_for_uri
    validate_identifiers_org_uri(object['uri'])
  File "/usr/local/lib/python3.9/site-packages/biosimulators_utils/utils/identifiers_org.py", line 185, in validate_identifiers_org_uri
    namespace = get_identifiers_org_namespace(match.group(2).lower())
  File "/usr/local/lib/python3.9/site-packages/biosimulators_utils/utils/identifiers_org.py", line 172, in get_identifiers_org_namespace
    return get_identifiers_org_namespaces()[prefix]
  File "/usr/local/lib/python3.9/site-packages/biosimulators_utils/utils/identifiers_org.py", line 142, in get_identifiers_org_namespaces
    pattern=re.compile(namespace['pattern']),
  File "/usr/local/lib/python3.9/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/local/lib/python3.9/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/lib/python3.9/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/lib/python3.9/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/local/lib/python3.9/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/local/lib/python3.9/sre_parse.py", line 554, in _parse
    code1 = _class_escape(source, this)
  File "/usr/local/lib/python3.9/sre_parse.py", line 349, in _class_escape
    raise source.error('bad escape %s' % escape, len(escape))
re.error: bad escape \p at position 37
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonrkarr** [comment]
This is already fixed with biosimulators-utils 0.1.157, but hasn't been deployed to `prod` yet.

I mentioned this yesterday, identifiers.org now has regex patterns that Python can't understand. I switched to a third-party package which supports more (less standardized) regex.

**Comment by jonrkarr** [comment]
`Pipfile`/`Pipefile.lock` have already been updated.

**Comment by jonrkarr** [comment]
See also biosimulators/Biosimulators_utils#90.

**Comment by jonrkarr** [comment]
@bilalshaikh42 it sounds like you need to update your version of biosimulators-utils to >= 0.1.157.

**Comment by bilalshaikh42** [comment]
This was running on a docker container. I had an incorrect tag for the latest version
