### ISSUE TITLE
🐛:  Error on project summary call

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4077]
### Location

BioSimulations API

### What happened?

Getting a 500 error on API call for summary

### What made it happen?

Noticed it in the logs. Have not tried to reproduce yet

### Version

Development (Deployed on a .dev domain)

### Relevant log output

```shell
[Nest] 1  - 01/18/2022, 11:23:36 PM   ERROR [DefaultFilter] TypeError: Cannot read properties of undefined (reading 'language')
46
TypeError: Cannot read properties of undefined (reading 'language')
45
    at /app/main.js:6568:39
44
    at Array.forEach (<anonymous>)
43
    at /app/main.js:6560:26
42
    at Array.forEach (<anonymous>)
41
    at SimulationRunService.<anonymous> (/app/main.js:6539:33)
40
    at Generator.next (<anonymous>)
39
    at fulfilled (/app/node_modules/tslib/tslib.js:114:62)
38
    at runMicrotasks (<anonymous>)
37
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[32m[Nest] 1  - [39m01/18/2022, 11:23:36 PM [32m    LOG[39m [38;5;3m[DefaultFilter] [39m[32mObject:[39m
{
  "error": [
    {
      "status": "500",
      "title": "Internal Server Error",
      "detail": "An unexpected error occurred",
      "meta": {
        "time": 1642548216106,
        "url": "/runs/618d8b2389c70421ab793fdf/summary"
      }
    }
  ]
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonrkarr** [comment]
This a VCell simulation. Probably related to the log not existing and the summary assuming logs exist.

**Comment by jonrkarr** [comment]
This is strange. Somehow the SED-ML specifications weren't saved properly, causing a required attribute to be undefined. Was this before the optimization was turned off?

I'll add additional error handling.
