### ISSUE TITLE
🐛: SSH connection fails after some time since last use 

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4099]
### Location

Other (please describe below)

### What happened?

When submitting a job after some time without activity, the SSH connection will be dead. However, this will not be caught until it is used again, causing the first job submission to fail. Caused by the changes in #4086 

### What made it happen?

Submit a job

### Version

Development (Deployed on a .dev domain)

### Relevant log output

```shell
[Nest] 777219  - 01/21/2022, 10:42:36 AM   DEBUG [SshService] Executing command
[Nest] 777219  - 01/21/2022, 10:42:36 AM   ERROR [SshService] Connection Error: Error: read ECONNRESET
[Nest] 777219  - 01/21/2022, 10:42:36 AM     LOG [SshService] Retrying SSH connection
[Nest] 777219  - 01/21/2022, 10:42:36 AM   ERROR [SshService] Error: No response from server
[Nest] 777219  - 01/21/2022, 10:42:36 AM   ERROR [SshService] Stream is null
[Nest] 777219  - 01/21/2022, 10:42:36 AM     LOG [SshService] Retrying SSH connection
[Nest] 777219  - 01/21/2022, 10:42:36 AM   ERROR [HpcService] The job for simulation run '61ead46b8ead62f482280bd9' could not be submitted.
[Nest] 777219  - 01/21/2022, 10:42:36 AM   DEBUG [SshService] Executing command
[Nest] 777219  - 01/21/2022, 10:42:36 AM   ERROR [DispatchProcessor] An error occurred in submitting an HPC job for simulation run '61ead46b8ead62f482280bd9': The job for simulation run '61ead46b8ead62f482280bd9' could not be submitted: Error: No response from server

/home/bilal/Projects/work/Biosimulations/node_modules/ssh2/lib/client.js:1095
      throw new Error('Not connected');
            ^
Error: Not connected
    at Client.exec (/home/bilal/Projects/work/Biosimulations/node_modules/ssh2/lib/client.js:1095:13)
    at /home/bilal/Projects/work/Biosimulations/dist/apps/dispatch-service/webpack:/biosimulations/apps/dispatch-service/src/app/services/ssh/ssh.service.ts:55:25
    at new Promise (<anonymous>)
    at SshService.<anonymous> (/home/bilal/Projects/work/Biosimulations/dist/apps/dispatch-service/webpack:/biosimulations/apps/dispatch-service/src/app/services/ssh/ssh.service.ts:50:12)
    at Generator.next (<anonymous>)
    at /home/bilal/Projects/work/Biosimulations/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/home/bilal/Projects/work/Biosimulations/node_modules/tslib/tslib.js:113:16)
    at SshService.execStringCommand (/home/bilal/Projects/work/Biosimulations/dist/apps/dispatch-service/main.js:946:64)
    at SshService.<anonymous> (/home/bilal/Projects/work/Biosimulations/dist/apps/dispatch-service/webpack:/biosimulations/apps/dispatch-service/src/app/services/ssh/ssh.service.ts:80:27)
    at Generator.next (<anonymous>)
    at fulfilled (/home/bilal/Projects/work/Biosimulations/node_modules/tslib/tslib.js:114:62)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bilalshaikh42** [comment]
Adressed in #4087
