### ISSUE TITLE
🐛: Results API endpoints throws 500 error

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4101]
### Location

runBiosimulations

### What happened?

Using either the API or web browser, we get 500 errors when getting results. This is caused by the HSDS returning a 404, but it is not clear why this is not being handled or retried properly. This might be due to retry logic being set up not to retry 404s which we do not want in this case, since intermittent issues with the s3 bucket will cause 404s from HSDS

### What made it happen?

Try to load visualizations, call results API with data

### Version

Production (Deployed on a .org domain), Development (Deployed on a .dev domain)

### Relevant log output

```shell
Error: Request failed with status code 404
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:293:11)
    at IncomingMessage.emit (node:events:402:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json',
      Authorization: 'Basic *********',
      'User-Agent': 'axios/0.24.0'
    },
    params: { domain: '61da6510837f3f112d0b6a4e.results' },
    withCredentials: true,
    method: 'get',
    url: 'http://hsds:80/datasets',
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'hsds',
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(async_id_symbol)]: 1055047,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'GET /datasets?domain=61da6510837f3f112d0b6a4e.results HTTP/1.1\r\n' +
      'Accept: application/json\r\n' +
      'Authorization: Basic *******' +
      'User-Agent: axios/0.24.0\r\n' +
      'Host: hsds\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/datasets?domain=61da6510837f3f112d0b6a4e.results',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 404,
      statusMessage: 'Not Found',
      client: [Socket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'http://hsds:80/datasets?domain=61da6510837f3f112d0b6a4e.results',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 10,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'hsds',
    protocol: 'http:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'http://hsds:80/datasets?domain=61da6510837f3f112d0b6a4e.results',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      authorization: [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  response: {
    status: 404,
    statusText: 'Not Found',
    headers: {
      'content-type': 'text/plain; charset=utf-8',
      'content-length': '14',
      date: 'Mon, 24 Jan 2022 17:40:04 GMT',
      server: 'Python/3.8 aiohttp/3.7.4.post0',
      connection: 'close'
    },
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      headers: [Object],
      params: [Object],
      withCredentials: true,
      method: 'get',
      url: 'http://hsds:80/datasets',
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /datasets?domain=61da6510837f3f112d0b6a4e.results HTTP/1.1\r\n' +
        'Accept: application/json\r\n' +
        'Authorization: Basic *******' +
        'User-Agent: axios/0.24.0\r\n' +
        'Host: hsds\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/datasets?domain=61da6510837f3f112d0b6a4e.results',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'hsds',
      protocol: 'http:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: '404: Not Found'
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
[32m[Nest] 1  - [39m01/24/2022, 5:40:04 PM [32m    LOG[39m [38;5;3m[DefaultFilter] [39m[32mObject:[39m
{
  "error": [
    {
      "status": "500",
      "title": "Internal Server Error",
      "detail": "An unexpected error occurred",
      "meta": {
        "time": 1643046004355,
        "url": "/results/61da6510837f3f112d0b6a4e/simulation.sedml%2Freaction_fluxes?includeData=true"
      }
    }
  ]
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bilalshaikh42** [comment]
This is being caused by the "db" and "domains.json" folders not being present on the prod uconn bucket. I have no idea how this data was lost, but the dataservice will not work without it. 

@jonrkarr this is unfortunately going to make any demos impossible. I'll try to fix this asap, but we would need to rerun all the examples and projects on prod to get this working. Thoughts?

**Comment by bilalshaikh42** [comment]
I think i found the issue. This commit https://github.com/biosimulations/deployment/commit/35dbcb38da7b3ee2ae9793e5c530567a1687e3fe actually fixed the loading of the configuration of HSDS properly. Before this, the config was not being loaded, but was using the default value of "biosimdev". This means that all the older data for the prod branch is also on the biosimdev bucket.

**Comment by bilalshaikh42** [comment]
This has been resolved for the existing simulations. We need to rerun the simulations and projects on the next deployment to production and update the deployment to use the correct buckets

**Comment by jonrkarr** [comment]
Seems like the buckets need to be inspected to ensure that data is being written to the correct locations.

I have at least one example working on my machine

**Comment by bilalshaikh42** [comment]
Yup, this is fixed now for all the current examples. I switched the prod hsds to use the dev uconn bucket which is where the data is

**Comment by bilalshaikh42** [comment]
Resolved for new deployment on Google cloud buckets
