### ISSUE TITLE
🐛: Existing runs broken by `SedStyle` changes

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4279]
### Location

runBiosimulations, BioSimulations

### What happened?

Loading a page for a project causes an error message to display. 

### What made it happen?

Load https://biosimulations.org/projects/NFAT-translocation-Tomida-EMBO-J-2003

### Version

Production (Deployed on a .org domain), Development (Deployed on a .dev domain)

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
TypeError: Cannot read properties of undefined (reading 'forEach')
    at Af (sed-document.ts:77:27)
    at view.service.ts:395:32
    at Array.forEach (<anonymous>)
    at view.service.ts:393:34
    at map.js:7:37
    at c._next (OperatorSubscriber.js:13:21)
    at c.next (Subscriber.js:31:18)
    at Subject.js:31:30
    at c (errorContext.js:19:9)
    at c.next (Subject.js:26:9)
handleError @ error-handler.ts:36
...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bilalshaikh42** [comment]
Relevant portion of the code: 
```ts
export function deserializeSedDocument(
  serializedSedDoc: SerializedSedDocument,
): SedDocument {
  serializedSedDoc = JSON.parse(JSON.stringify(serializedSedDoc));

  const styleIdMap: IdMap<SedStyle> = {};
  serializedSedDoc.styles.forEach(
    (serializedStyle: SerializedSedStyle): void => {
      const style: SedStyle = (styleIdMap[serializedStyle.id] = {
        _type: serializedStyle._type,
        id: serializedStyle.id,
        name: serializedStyle?.name,
      });

      if (serializedStyle?.line) {
        style.line = Object.assign({}, serializedStyle.line);
      }
      if (serializedStyle?.marker) {
        style.marker = Object.assign({}, serializedStyle.marker);
      }
      if (serializedStyle?.fill) {
        style.fill = Object.assign({}, serializedStyle.fill);
      }
    },
  );

  serializedSedDoc.styles.forEach(
    (serializedStyle: SerializedSedStyle): void => {
      const style: SedStyle = styleIdMap[serializedStyle.id];
      if (serializedStyle?.base) {
        style.base = styleIdMap?.[serializedStyle.base];
      }
    },
  );
```
```serializedSedDoc.styles``` likely needs to be initialized to an empty array if it is undefined. Ideally the API would just send an empty array in this case.

**Comment by jonrkarr** [comment]
I forgot to provide backward handling for older documents stored in the database.
