### ISSUE TITLE
🐛: COMBINE API Swagger app UI gives 500 error

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4292]
### Location

Other (please describe below)

### What happened?

The Combine API is crashing when loading the main documentation or the API specifications

### What made it happen?

Open up [https://combine.api.biosimulations.org](https://combine.api.biosimulations.org)

### Version

Production (Deployed on a .org domain)

### Relevant log output

```shell
TypeError: datetime.datetime(2018, 1, 17, 0, 0, tzinfo=datetime.timezone.utc) is not JSON serializable
92
[2022-02-20 09:47:25,464] ERROR in app: Exception on /openapi.json [GET]
91
Traceback (most recent call last):
90
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
89
    response = self.full_dispatch_request()
88
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
87
    rv = self.handle_user_exception(e)
86
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
85
    return cors_after_request(app.make_response(f(*args, **kwargs)))
84
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
83
    rv = self.dispatch_request()
82
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
81
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
80
  File "/usr/local/lib/python3.9/site-packages/connexion/apis/flask_api.py", line 320, in get_json_spec
79
    return flask.jsonify(self._spec_for_prefix())
78
  File "/usr/local/lib/python3.9/site-packages/flask/json/__init__.py", line 361, in jsonify
77
    f"{dumps(data, indent=indent, separators=separators)}\n",
76
  File "/usr/local/lib/python3.9/site-packages/flask/json/__init__.py", line 139, in dumps
75
    rv = _json.dumps(obj, **kwargs)
74
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
73
    return cls(
72
  File "/app/src/app.py", line 69, in encode
71
    return ujson.dumps(o)
70
TypeError: datetime.datetime(2018, 1, 17, 0, 0, tzinfo=datetime.timezone.utc) is not JSON serializable
69
[2022-02-20 09:47:29,360] ERROR in app: Exception on /openapi.json [GET]
68
Traceback (most recent call last):
67
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
66
    response = self.full_dispatch_request()
65
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
64
    rv = self.handle_user_exception(e)
63
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
62
    return cors_after_request(app.make_response(f(*args, **kwargs)))
61
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
60
    rv = self.dispatch_request()
59
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
58
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
57
  File "/usr/local/lib/python3.9/site-packages/connexion/apis/flask_api.py", line 320, in get_json_spec
56
    return flask.jsonify(self._spec_for_prefix())
55
  File "/usr/local/lib/python3.9/site-packages/flask/json/__init__.py", line 361, in jsonify
54
    f"{dumps(data, indent=indent, separators=separators)}\n",
53
  File "/usr/local/lib/python3.9/site-packages/flask/json/__init__.py", line 139, in dumps
52
    rv = _json.dumps(obj, **kwargs)
51
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
50
    return cls(
49
  File "/app/src/app.py", line 69, in encode
48
    return ujson.dumps(o)
47
TypeError: datetime.datetime(2018, 1, 17, 0, 0, tzinfo=datetime.timezone.utc) is not JSON serializable
46
[2022-02-21 01:43:21,827] ERROR in app: Exception on /openapi.json [GET]
45
Traceback (most recent call last):
44
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
43
    response = self.full_dispatch_request()
42
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
41
    rv = self.handle_user_exception(e)
40
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
39
    return cors_after_request(app.make_response(f(*args, **kwargs)))
38
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
37
    rv = self.dispatch_request()
36
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
35
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
34
  File "/usr/local/lib/python3.9/site-packages/connexion/apis/flask_api.py", line 320, in get_json_spec
33
    return flask.jsonify(self._spec_for_prefix())
32
  File "/usr/local/lib/python3.9/site-packages/flask/json/__init__.py", line 361, in jsonify
31
    f"{dumps(data, indent=indent, separators=separators)}\n",
30
  File "/usr/local/lib/python3.9/site-packages/flask/json/__init__.py", line 139, in dumps
29
    rv = _json.dumps(obj, **kwargs)
28
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
27
    return cls(
26
  File "/app/src/app.py", line 69, in encode
25
    return ujson.dumps(o)
24
TypeError: datetime.datetime(2018, 1, 17, 0, 0, tzinfo=datetime.timezone.utc) is not JSON serializable
23
[2022-02-21 19:43:24,388] ERROR in app: Exception on /openapi.json [GET]
22
Traceback (most recent call last):
21
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
20
    response = self.full_dispatch_request()
19
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
18
    rv = self.handle_user_exception(e)
17
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
16
    return cors_after_request(app.make_response(f(*args, **kwargs)))
15
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
14
    rv = self.dispatch_request()
13
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
12
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
11
  File "/usr/local/lib/python3.9/site-packages/connexion/apis/flask_api.py", line 320, in get_json_spec
10
    return flask.jsonify(self._spec_for_prefix())
9
  File "/usr/local/lib/python3.9/site-packages/flask/json/__init__.py", line 361, in jsonify
8
    f"{dumps(data, indent=indent, separators=separators)}\n",
7
  File "/usr/local/lib/python3.9/site-packages/flask/json/__init__.py", line 139, in dumps
6
    rv = _json.dumps(obj, **kwargs)
5
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
4
    return cls(
3
  File "/app/src/app.py", line 69, in encode
2
    return ujson.dumps(o)
1
TypeError: datetime.datetime(2018, 1, 17, 0, 0, tzinfo=datetime.timezone.utc) is not JSON serializable
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonrkarr** [comment]
Caused by trying to speed up JSON serialization in the COMBINE API by replacing the standard json with ujson. This should have only affected the Swagger UI app, not the execution of the endpoints.

Todo
- [x] Switch JSON serialization to orjson
- [x] Add unit test for Swagger UI app
