### ISSUE TITLE
45 of 74 ModelDB runs did not succeed for multiple reasons

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#4319]
The first number in each bullet is the ModelDB id of the project. The corresponding COMBINE archives in https://github.com/biosimulations/biosimulations-modeldb/tree/dev/biosimulations_modeldb/final/projects.

- [x] Thumbnails in sub directories could not be saved -- See #4318 
  - 31 projects
- [x] Failed to extract file -- see #4329 
  - Unpacked contents of archive not uploaded to S3
  - This error is reproducible.
  - Examples 
    - 229640: `621958e10df8c75a0ac00ca7`
    - 152028: `621958d12f0784cadefe366b`
    - 206365: `621958da0df8c75a0ac00bf4`
  - These are the archives with the largest number of files (258, 331, and 3705). 
  - The biggest successful archive have 109 files
  - The extraction appears to fail when archives have many files
- [ ] Stuck in post-processing
  - May be due to failures with extraction
  - Still running a day later -- this reveals that there's also issue with error handling
  - Example
    - 228337: `621958df2f0784cadefe3730`
- [x] hsload failed
  - This does reveal an issue with hsload -- reported as HDFGroup/h5pyd#116
  - However, the real problems for us aren't hsload, but failures to correctly handle XPP
  - Examples  
    - [x] 83570: `621958bc2345ec060040d0b8` -- simulation failed because not executed from correct working directory
    - [x] 185334: `621958d50df8c75a0ac00bb4` -- invalid model file
    - [x] 227577: `621958dd0df8c75a0ac00c39`-- simulation results because not executed from correct working directory
- [ ] Failed to publish -- does this need to be retried?
  - 58195: `621958b50df8c75a0ac00a9c`
  - 145800: `621958cd2f0784cadefe3641`
  - 151677: `621958d02f0784cadefe3664`
- [ ] Failed to updated published run -- does this need to be retried?
  - 35358: `621958b22f0784cadefe3595`
  - 45513: `621958b30df8c75a0ac00a94`
  - 57910: `621958b32f0784cadefe359c`
  - 58172: `621958b40df8c75a0ac00a97` 

## Example hsload failure
```
Traceback (most recent call last):
  File "h5py/h5o.pyx", line 302, in h5py.h5o.cb_obj_simple
  File "/home/FCAM/crbmapi/.local/lib/python3.6/site-packages/h5py/_hl/group.py", line 591, in proxy
    return func(name, self[name])
  File "/usr/local/lib/python3.6/site-packages/h5pyd/_apps/utillib.py", line 674, in object_create_helper
    create_dataset(obj, ctx)
  File "/usr/local/lib/python3.6/site-packages/h5pyd/_apps/utillib.py", line 459, in create_dataset
    fillvalue=fillvalue, scaleoffset=scaleoffset)
  File "/usr/local/lib/python3.6/site-packages/h5pyd/_hl/group.py", line 337, in create_dataset
    dsid = dataset.make_new_dset(self, shape=shape, dtype=dtype, **kwds)
  File "/usr/local/lib/python3.6/site-packages/h5pyd/_hl/dataset.py", line 129, in make_new_dset
    raise ValueError(errmsg)
ValueError: Chunk shape must not be greater than data shape in any dimension. (1, 1024) is not compatible with (2, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/hsload", line 33, in 
    sys.exit(load_entry_point('h5pyd==0.8.4', 'console_scripts', 'hsload')())
  File "/usr/local/lib/python3.6/site-packages/h5pyd/_apps/hsload.py", line 314, in main
    load_file(fin, fout, verbose=verbose, dataload=dataload, s3path=s3path, compression=compression, compression_opts=compression_opts)
  File "/usr/local/lib/python3.6/site-packages/h5pyd/_apps/utillib.py", line 714, in load_file
    fin.visititems(object_create_helper)
  File "/home/FCAM/crbmapi/.local/lib/python3.6/site-packages/h5py/_hl/group.py", line 592, in visititems
    return h5o.visit(self.id, proxy)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
```

**Comment by bilalshaikh42** [comment]
The hsload issue seems to be either a dependent issue or something wrong with the shape of the HDF5 file based on the error. Is this an intermittent problem, or does it occur consistently?

**Comment by jonrkarr** [comment]
The hsload issue is an real bug with hsload. Incidentally, it revealed another issue with the results which I fixed.

Results from next run are in #4339 and #4340.
